"""Automox MCP workflows - consolidated exports."""

from __future__ import annotations

from . import (
    account,
    audit,
    audit_v2,
    compound,
    data_extracts,
    device_commands,
    device_inventory,
    device_search,
    devices,
    events,
    groups,
    packages,
    policy,
    policy_crud,
    policy_history,
    policy_windows,
    reports,
    vuln_sync,
    webhooks,
    worklets,
)
from .account import (
    create_global_api_key,
    create_user_api_key,
    create_zone,
    delete_global_api_key,
    delete_user_api_key,
    get_account,
    get_account_user,
    get_user,
    get_user_api_key,
    get_zone,
    invite_user_to_account,
    list_account_rbac_roles,
    list_global_api_keys,
    list_org_api_keys,
    list_organizations,
    list_user_api_keys,
    list_users,
    list_zone_users,
    list_zones,
    list_zones_for_user,
    remove_user_from_account,
    update_global_api_key,
    update_user,
    update_user_api_key,
)
from .audit import audit_trail_user_activity
from .audit_v2 import audit_events_ocsf
from .compound import get_compliance_snapshot, get_device_full_profile, get_patch_tuesday_readiness
from .data_extracts import create_data_extract, get_data_extract, list_data_extracts
from .device_commands import issue_device_command
from .device_inventory import get_device_inventory, get_device_inventory_categories
from .device_search import (
    advanced_device_search,
    assign_policies_to_saved_search,
    create_saved_search,
    delete_saved_search,
    device_search_typeahead,
    get_cached_search_results,
    get_device_assignments,
    get_device_by_uuid,
    get_device_metadata_fields,
    get_saved_search,
    get_saved_search_results,
    get_search_scopes,
    get_searchable_fields,
    list_saved_searches,
    list_searches_for_device,
    refresh_saved_search_cache,
    run_saved_search,
    update_saved_search,
)
from .devices import (
    batch_update_devices,
    describe_device,
    list_device_inventory,
    list_devices_needing_attention,
    search_devices,
    summarize_device_health,
)
from .events import list_events
from .groups import (
    create_server_group,
    delete_server_group,
    get_server_group,
    list_server_groups,
    update_server_group,
)
from .packages import list_device_packages, search_org_packages
from .policy import (
    describe_policy,
    describe_policy_run_result,
    get_policy_compliance_stats,
    summarize_patch_approvals,
    summarize_policies,
    summarize_policy_activity,
    summarize_policy_execution_history,
)
from .policy_crud import (
    apply_policy_changes,
    clone_policy,
    delete_policy,
    execute_policy,
    list_devices_for_policies,
    normalize_policy_operations_input,
    preview_policy_device_filters,
    resolve_patch_approval,
)
from .policy_history import (
    get_policy_history_detail,
    get_policy_run_detail_v2,
    get_policy_runs_for_policy,
    list_policy_execution_counts,
    list_policy_runs_v2,
    policy_run_count,
    policy_runs_by_policy,
)
from .policy_windows import (
    check_group_exclusion_status,
    check_window_active,
    create_policy_window,
    delete_policy_window,
    get_device_scheduled_windows,
    get_group_scheduled_windows,
    get_policy_window,
    search_policy_windows,
    update_policy_window,
)
from .reports import get_noncompliant_report, get_prepatch_report
from .splashtop import (
    bulk_install_uninstall as splashtop_bulk_install_uninstall,
)
from .splashtop import (
    force_disconnect as splashtop_force_disconnect,
)
from .splashtop import (
    get_attended_access as splashtop_get_attended_access,
)
from .splashtop import (
    get_device_status as splashtop_get_device_status,
)
from .splashtop import (
    get_session_status as splashtop_get_session_status,
)
from .splashtop import (
    initiate_connection as splashtop_initiate_connection,
)
from .splashtop import (
    install_splashtop,
    uninstall_splashtop,
)
from .splashtop import (
    set_attended_access as splashtop_set_attended_access,
)
from .splashtop import (
    set_bulk_attended_access as splashtop_set_bulk_attended_access,
)
from .vuln_sync import (
    apply_remediation_actions,
    get_action_set_detail,
    get_action_set_issues,
    get_action_set_solutions,
    get_upload_formats,
    list_remediation_action_sets,
    upload_action_set,
)
from .webhooks import (
    create_webhook,
    delete_webhook,
    get_webhook,
    list_webhook_event_types,
    list_webhooks,
    rotate_webhook_secret,
    test_webhook,
    update_webhook,
)
from .worklets import get_worklet_detail, search_worklet_catalog

__all__ = [
    "account",
    "audit",
    "audit_v2",
    "compound",
    "data_extracts",
    "device_commands",
    "device_inventory",
    "device_search",
    "devices",
    "events",
    "groups",
    "packages",
    "policy",
    "policy_crud",
    "policy_history",
    "policy_windows",
    "reports",
    "splashtop",
    "vuln_sync",
    "webhooks",
    "worklets",
    "advanced_device_search",
    "apply_policy_changes",
    "assign_policies_to_saved_search",
    "apply_remediation_actions",
    "audit_events_ocsf",
    "audit_trail_user_activity",
    "batch_update_devices",
    "clone_policy",
    "create_data_extract",
    "create_global_api_key",
    "create_saved_search",
    "create_server_group",
    "create_user_api_key",
    "create_webhook",
    "create_zone",
    "delete_policy",
    "delete_global_api_key",
    "delete_saved_search",
    "delete_server_group",
    "delete_user_api_key",
    "delete_webhook",
    "describe_device",
    "describe_policy",
    "describe_policy_run_result",
    "get_account",
    "get_account_user",
    "get_user",
    "get_user_api_key",
    "get_zone",
    "device_search_typeahead",
    "execute_policy",
    "get_action_set_detail",
    "get_action_set_issues",
    "get_action_set_solutions",
    "get_cached_search_results",
    "get_compliance_snapshot",
    "get_data_extract",
    "get_device_assignments",
    "get_device_by_uuid",
    "get_device_full_profile",
    "get_device_inventory",
    "get_device_inventory_categories",
    "get_device_metadata_fields",
    "get_noncompliant_report",
    "get_patch_tuesday_readiness",
    "get_policy_compliance_stats",
    "get_policy_history_detail",
    "get_policy_run_detail_v2",
    "get_policy_runs_for_policy",
    "get_prepatch_report",
    "get_saved_search",
    "get_saved_search_results",
    "get_search_scopes",
    "get_searchable_fields",
    "get_server_group",
    "get_upload_formats",
    "get_webhook",
    "get_worklet_detail",
    "install_splashtop",
    "invite_user_to_account",
    "issue_device_command",
    "list_data_extracts",
    "list_devices_for_policies",
    "list_device_inventory",
    "list_device_packages",
    "list_devices_needing_attention",
    "list_events",
    "list_account_rbac_roles",
    "list_global_api_keys",
    "list_org_api_keys",
    "list_organizations",
    "list_user_api_keys",
    "list_users",
    "list_zone_users",
    "list_zones",
    "list_zones_for_user",
    "list_policy_execution_counts",
    "list_policy_runs_v2",
    "list_remediation_action_sets",
    "list_saved_searches",
    "list_searches_for_device",
    "list_server_groups",
    "list_webhook_event_types",
    "list_webhooks",
    "normalize_policy_operations_input",
    "preview_policy_device_filters",
    "refresh_saved_search_cache",
    "run_saved_search",
    "policy_run_count",
    "policy_runs_by_policy",
    "remove_user_from_account",
    "resolve_patch_approval",
    "rotate_webhook_secret",
    "search_devices",
    "search_org_packages",
    "search_worklet_catalog",
    "splashtop_bulk_install_uninstall",
    "splashtop_force_disconnect",
    "splashtop_get_attended_access",
    "splashtop_get_device_status",
    "splashtop_get_session_status",
    "splashtop_initiate_connection",
    "splashtop_set_attended_access",
    "splashtop_set_bulk_attended_access",
    "summarize_device_health",
    "summarize_patch_approvals",
    "summarize_policies",
    "summarize_policy_activity",
    "summarize_policy_execution_history",
    "test_webhook",
    "update_global_api_key",
    "update_user",
    "update_user_api_key",
    "uninstall_splashtop",
    "update_saved_search",
    "update_server_group",
    "update_webhook",
    "upload_action_set",
    "check_group_exclusion_status",
    "check_window_active",
    "create_policy_window",
    "delete_policy_window",
    "get_device_scheduled_windows",
    "get_group_scheduled_windows",
    "get_policy_window",
    "search_policy_windows",
    "update_policy_window",
]
