"""Automox MCP workflows - consolidated exports."""

from __future__ import annotations

from . import (
    account,
    audit,
    audit_v2,
    compound,
    data_extracts,
    device_commands,
    device_inventory,
    device_search,
    devices,
    events,
    groups,
    packages,
    policy,
    policy_crud,
    policy_history,
    policy_windows,
    reports,
    vuln_sync,
    webhooks,
    worklets,
)
from .account import invite_user_to_account, list_org_api_keys, remove_user_from_account
from .audit import audit_trail_user_activity
from .audit_v2 import audit_events_ocsf
from .compound import get_compliance_snapshot, get_device_full_profile, get_patch_tuesday_readiness
from .data_extracts import create_data_extract, get_data_extract, list_data_extracts
from .device_commands import issue_device_command
from .device_inventory import get_device_inventory, get_device_inventory_categories
from .device_search import (
    advanced_device_search,
    device_search_typeahead,
    get_device_assignments,
    get_device_by_uuid,
    get_device_metadata_fields,
    list_saved_searches,
)
from .devices import (
    describe_device,
    list_device_inventory,
    list_devices_needing_attention,
    search_devices,
    summarize_device_health,
)
from .events import list_events
from .groups import (
    create_server_group,
    delete_server_group,
    get_server_group,
    list_server_groups,
    update_server_group,
)
from .packages import list_device_packages, search_org_packages
from .policy import (
    describe_policy,
    describe_policy_run_result,
    get_policy_compliance_stats,
    summarize_patch_approvals,
    summarize_policies,
    summarize_policy_activity,
    summarize_policy_execution_history,
)
from .policy_crud import (
    apply_policy_changes,
    clone_policy,
    delete_policy,
    execute_policy,
    normalize_policy_operations_input,
    resolve_patch_approval,
)
from .policy_history import (
    get_policy_history_detail,
    get_policy_run_detail_v2,
    get_policy_runs_for_policy,
    list_policy_runs_v2,
    policy_run_count,
    policy_runs_by_policy,
)
from .reports import get_noncompliant_report, get_prepatch_report
from .vuln_sync import (
    get_action_set_actions,
    get_action_set_detail,
    get_action_set_issues,
    get_action_set_solutions,
    get_upload_formats,
    list_remediation_action_sets,
    upload_action_set,
)
from .webhooks import (
    create_webhook,
    delete_webhook,
    get_webhook,
    list_webhook_event_types,
    list_webhooks,
    rotate_webhook_secret,
    test_webhook,
    update_webhook,
)
from .policy_windows import (
    check_group_exclusion_status,
    check_window_active,
    create_policy_window,
    delete_policy_window,
    get_device_scheduled_windows,
    get_group_scheduled_windows,
    get_policy_window,
    search_policy_windows,
    update_policy_window,
)
from .worklets import get_worklet_detail, search_worklet_catalog

__all__ = [
    "account",
    "audit",
    "audit_v2",
    "compound",
    "data_extracts",
    "device_commands",
    "device_inventory",
    "device_search",
    "devices",
    "events",
    "groups",
    "packages",
    "policy",
    "policy_crud",
    "policy_history",
    "policy_windows",
    "reports",
    "vuln_sync",
    "webhooks",
    "worklets",
    "advanced_device_search",
    "apply_policy_changes",
    "audit_events_ocsf",
    "audit_trail_user_activity",
    "clone_policy",
    "create_data_extract",
    "create_server_group",
    "create_webhook",
    "delete_policy",
    "delete_server_group",
    "delete_webhook",
    "describe_device",
    "describe_policy",
    "describe_policy_run_result",
    "device_search_typeahead",
    "execute_policy",
    "get_action_set_actions",
    "get_action_set_detail",
    "get_action_set_issues",
    "get_action_set_solutions",
    "get_compliance_snapshot",
    "get_data_extract",
    "get_device_assignments",
    "get_device_by_uuid",
    "get_device_full_profile",
    "get_device_inventory",
    "get_device_inventory_categories",
    "get_device_metadata_fields",
    "get_noncompliant_report",
    "get_patch_tuesday_readiness",
    "get_policy_compliance_stats",
    "get_policy_history_detail",
    "get_policy_run_detail_v2",
    "get_policy_runs_for_policy",
    "get_prepatch_report",
    "get_server_group",
    "get_upload_formats",
    "get_webhook",
    "get_worklet_detail",
    "invite_user_to_account",
    "issue_device_command",
    "list_data_extracts",
    "list_device_inventory",
    "list_device_packages",
    "list_devices_needing_attention",
    "list_events",
    "list_org_api_keys",
    "list_policy_runs_v2",
    "list_remediation_action_sets",
    "list_saved_searches",
    "list_server_groups",
    "list_webhook_event_types",
    "list_webhooks",
    "normalize_policy_operations_input",
    "policy_run_count",
    "policy_runs_by_policy",
    "remove_user_from_account",
    "resolve_patch_approval",
    "rotate_webhook_secret",
    "search_devices",
    "search_org_packages",
    "search_worklet_catalog",
    "summarize_device_health",
    "summarize_patch_approvals",
    "summarize_policies",
    "summarize_policy_activity",
    "summarize_policy_execution_history",
    "test_webhook",
    "update_server_group",
    "update_webhook",
    "upload_action_set",
    "check_group_exclusion_status",
    "check_window_active",
    "create_policy_window",
    "delete_policy_window",
    "get_device_scheduled_windows",
    "get_group_scheduled_windows",
    "get_policy_window",
    "search_policy_windows",
    "update_policy_window",
]
